name: Test Upload Artifact Access
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Upload dummy artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: README.md
